import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const base=process.env.SPROUT_DEMO_BASE_URL||'http://127.0.0.1:5173';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1512,height:1120}});
await fs.mkdir('docs/screenshots',{recursive:true});
await page.goto(base);await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:'docs/screenshots/studio-home.png'});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'docs/screenshots/studio-mobile.png'});
await page.setViewportSize({width:1512,height:1050});
const {projects}=await (await page.request.get(base+'/api/studio/projects')).json();
const star=projects.find(p=>p.template==='star-catcher'&&p.modules.every(m=>m.status==='done'));
if(!star)throw Error('Run node scripts/seed-studio-demo.mjs first.');
await page.addInitScript(()=>{Math.random=()=>0.5});await page.clock.install();
await page.goto(base+'/#project='+star.id);
await page.getByRole('button',{name:'作品预览',exact:true}).click();
const frame=page.frameLocator('iframe[title="作品试玩"]');
await frame.locator('body').evaluate(async()=>{await document.fonts.ready;});
await page.waitForFunction(()=>{const frame=document.querySelector('iframe');return frame?.srcdoc.includes('SproutPreview');});
await frame.locator('body').evaluate(async()=>{await document.fonts.ready;});
await frame.getByRole('button',{name:'开始接星星'}).click();
await page.clock.runFor(4000);
await page.screenshot({path:'docs/screenshots/studio-project.png'});
const font=await frame.locator('body').evaluate(()=>[...document.fonts].map(f=>({family:f.family,status:f.status})));
await fs.writeFile('reports/screenshots-validation.json',JSON.stringify({capturedAt:new Date().toISOString(),base,project:star.id,previewFonts:font,embeddedLicense:await page.locator('iframe').evaluate(f=>f.srcdoc.includes('SIL OPEN FONT LICENSE')),systemFontOverride:false},null,2));
await browser.close();
console.log('Captured desktop, mobile and running vector game, with embedded preview font.');
